const CONSTANTS = {};

CONSTANTS.SECRETKEY_PATTERN = '^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^a-zA-Z0-9\\s]).{8,16}$';
CONSTANTS.DEFAULT_PUBLIC_PROFILE = 'No public profile is set.';

CONSTANTS.BCRYPT_SALTROUNDS = 10;

CONSTANTS.HTTP_STATUS_BAD_REQUEST = 400;
CONSTANTS.HTTP_STATUS_CONFLICT = 409;

module.exports = CONSTANTS;
