const CONSTANTS = {};

CONSTANTS.SECRETKEY_PATTERN = '^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^a-zA-Z0-9\\s]).{8,16}$';
CONSTANTS.JWT_TOKEN_EXPIRY = '2d';
CONSTANTS.JWT_TOKEN_PREFIX = 'Bearer';
CONSTANTS.JWT_HEADER_STRING = 'Authorization';

CONSTANTS.DEFAULT_PUBLIC_PROFILE = 'No public profile is set.';

CONSTANTS.BCRYPT_SALTROUNDS = 10;

CONSTANTS.HTTP_STATUS_SERVER_ERROR = 500;
CONSTANTS.HTTP_STATUS_BAD_REQUEST = 400;
CONSTANTS.HTTP_STATUS_CONFLICT = 409;
CONSTANTS.HTTP_STATUS_OK = 200;
CONSTANTS.HTTP_STATUS_UNAUTHORIZED = 401;
CONSTANTS.HTTP_STATUS_FORBIDDEN = 403;

CONSTANTS.EMAIL_TEMPLATE_CREATE_USER = 'createuser';
CONSTANTS.EMAIL_TEMPLATE_FORGET_PWD = 'forgetpwd';
CONSTANTS.EMAIL_TEMPLATE_CONTACTUS = 'contactus';

module.exports = CONSTANTS;
